name: Docs

on:
  push:
    branches:
      - main
    paths:
      # Run when documentation changes
      - 'docs/**'
      # Run when Python source changes
      - 'src/**'
      # Run when pyproject or workflow changes
      - 'pyproject.toml'
      - '.github/workflows/docs.yml'

jobs:
  build-and-test:
    name: Build and Deploy Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Install main package with optional dev and docs dependencies
      - name: Install package and dev/docs dependencies
        run: |
          python -m pip install -e .[dev,docs,ccsds]

      # Build Sphinx docs
      - name: Build Sphinx docs
        run: |
          cd docs
          if [ -f Makefile ]; then
            make html
          else
            sphinx-build -b html . _build/html
          fi

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"